# yaml-language-server: $schema=https://json-schema.axonivy.com/config/14.0.0/databases.json
Databases:
  stock:
    Url: jdbc:hsqldb:mem:StockDb
    Driver: org.hsqldb.jdbcDriver
  invalidDB:
    Url: jdbc:postgresql://null/InvalidDB
    Driver: org.postgresql.Driver
    UserName: ''
    Properties:
      This DB is invalid on purpose: so it can be used to throw an error
