# yaml-language-server: $schema=https://json-schema.axonivy.com/config/14.0.0/webservice-clients.json
WebServiceClients:
  factory:
    Id: 16FEC3EAEC5333CC
    WsdlUrl: http://localhost:9999/designer/ws/NikeProject/16FEAF30FCA53A53?WSDL
    WsCallLibrary: CXF
    ServiceClass: nike.project.client.NikeFactoryService
    Endpoints:
      NikeFactoryPort:
        - http://localhost:8082/designer/ws/NikeProject/16FEAF30FCA53A53
