# yaml-language-server: $schema=https://json-schema.axonivy.com/14.0-dev/config/databases.json
Databases:
  FootballDB:
    Url: jdbc:hsqldb:mem:Football
    Driver: org.hsqldb.jdbc.JDBCDriver
    Password: ${decrypt:}
