# yaml-language-server: $schema=https://json-schema.axonivy.com/config/14.0.0/users.json
Users:
  - Name: theBoss
    Password: theBoss
    Roles:
      - Boss
  - Name: theWorker
    Password: theWorker
    Roles:
      - Team
